TasksArray Creation             
Create a 1D array of numbers from 10 to 50.              
Create a 3x3 array of random numbers between 0 and 1.           
Array Attributes             
Find the shape, size, and data type of the array you created in the previous task.             
Basic Operations             
Add 5 to every element of a 1D array.                
Multiply two 2D arrays element-wise.              
Indexing and Slicing             
Create a 5x5 array of integers from 1 to 25. Extract:              
The first row.               
The last column.              
A subarray of the first three rows and first two columns.             
Aggregation             
Create a 10-element array of random integers between 10 and 100. Find:      
The maximum value.          
The minimum value.           
The mean and standard deviation.         
Reshaping        
Convert a 1D array of numbers from 1 to 12 into a 3x4 matrix.         
Broadcasting              
Create a 3x3 matrix of ones. Add a 1D array [1, 2, 3] to each row.        
Filtering         
Create a 1D array of random integers between 1 and 50. Extract all elements that are divisible by 5.            
Matrix Multiplication            
Create two 2x2 matrices and perform matrix multiplication.             
Advanced Indexing           
Given a 4x4 array, use fancy indexing to extract the diagonal elements.


In [ ]:
import numpy as np
Arr=np.arange(10,50)
print(Arr)
print()
Arr1=np.random.rand(3,3)
print(Arr1)
print()


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

[[0.8218072  0.4714692  0.23183721]
 [0.80754447 0.15589052 0.55686554]
 [0.90229539 0.58145795 0.92844418]]



In [ ]:
#1
print("Array attributes:")
print("Size of array 1: ",np.size(Arr))
print("Size of array 2: ",np.size(Arr1))
print("Shape of array 1: ",np.shape(Arr))
print("Shape of array 2: ",np.shape(Arr1))
print("Data type of array 1: ",Arr.dtype)
print("Data type of array 2: ",Arr1.dtype)


Array attributes:
Size of array 1:  40
Size of array 2:  9
Shape of array 1:  (40,)
Shape of array 2:  (3, 3)
Data type of array 1:  int64
Data type of array 2:  float64


In [ ]:
#2
print("Basic Operations")
Arr=Arr+5
print("Added 5 to every element: ",Arr)
Arr2=np.random.rand(3,3)
print("Multiplication of two arrays:\n ",Arr1*Arr2)


Basic Operations
Added 5 to every element:  [25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64]
Multiplication of two arrays:
  [[0.35790089 0.37789526 0.06508106]
 [0.74971478 0.0011616  0.27182721]
 [0.85784557 0.19074912 0.59106819]]


In [ ]:
#3
Arr3=np.arange(1,26)
Arr3=Arr3.reshape(5,5)
print(Arr3)
print("First row: ",Arr3[0])
print("Last column: ",Arr3[:,-1])
print("Subarray: \n",Arr3[:3,:2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
First row:  [1 2 3 4 5]
Last column:  [ 5 10 15 20 25]
Subarray: 
 [[ 1  2]
 [ 6  7]
 [11 12]]


In [ ]:
#4
Arr4=np.random.randint(10,100,10)
print(Arr4)
print("Maximum value: ",np.max(Arr4))
print("Minimum value: ",np.min(Arr4))
print("Mean: ",np.mean(Arr4))
print("Standard deviation: ",np.std(Arr4))

[65 87 49 53 59 40 74 98 89 59]
Maximum value:  98
Minimum value:  40
Mean:  67.3
Standard deviation:  18.09447429465692


In [ ]:
#6
Arr5=np.arange(1,13)
Arr5=Arr5.reshape(3,4)
print(Arr5)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
#7
Arr6=np.ones((3,3))
print(Arr6)
Arr6=Arr6+np.array([1,2,3])
print(Arr6)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


In [ ]:
#8
Arr7=np.random.randint(1,50,50)
print(Arr7)
Arr7=Arr7[Arr7%5==0]
print(Arr7)

[23  9 21 40 21  3 21 21  2 27 35 44 22 43 41  4 25 24 24 46 34 44 15 25
 27 36  9  6  9  5 32 39 38 13 29 16  2  3  1 42 10 17 19 22 27 23 11  4
  9  2]
[40 35 25 15 25  5 10]


In [ ]:
#9
Arr8=np.random.rand(2,2)
Arr9=np.random.rand(2,2)
print(Arr8)
print(Arr9)
print(np.matmul(Arr8,Arr9))

[[0.61995497 0.44504824]
 [0.08906821 0.87411844]]
[[0.97800553 0.57165459]
 [0.53771765 0.06052311]]
[[0.84562968 0.3813358 ]
 [0.55713812 0.10382061]]


In [ ]:
#10
Arr10=np.random.randint(1,100,4)
print(Arr10)
print(np.diag(Arr10))

[44  4 21 41]
[[44  0  0  0]
 [ 0  4  0  0]
 [ 0  0 21  0]
 [ 0  0  0 41]]
